
[waystones]
	#Allow Pokemon to be used for Waystone teleportation.
	allowWaystoneTeleport = true
	#Does the Pokemon need to have Teleport accessible. If false, any psychic type can teleport.
	requireTeleportMove = true
	#Minimum level to Teleport.
	#Range: 0 ~ 255
	waystoneMinTeleportLevel = 0

